name = "OPT-ClientMod"
modname = "opt-client"
prefix = "opt_client"
author = "Operation Pandora Trigger"

files = [
    "mod.cpp",
    "readme.md",
    "opt4_icon.paa",
    "extras/addons",
    "extras/keys"
]

releasebuild = [
#    "@zip opt-clientmod_v{{semver.major}}.{{semver.minor}}.{{semver.patch}}.{{semver.build}}"
]

key_name = "opt_client_v{{semver.major}}.{{semver.minor}}.{{semver.patch}}.{{semver.build}}"
authority = "opt_client_v{{semver.major}}.{{semver.minor}}.{{semver.patch}}.{{semver.build}}"
