name = "OPT-ClientMod"
modname = "opt-client"
prefix = "opt_client"
author = "Operation Pandora Trigger"

files = [
    "mod.cpp",
    "README.md",
    "opt4_icon.paa",
    "extras/addons"
]

releasebuild = [
    "@zip opt-clientmod_v{{semver.major}}.{{semver.minor}}.{{semver.patch}}.{{semver.build}}"
]

key_name = "v{{semver.major}}.{{semver.minor}}.{{semver.patch}}.{{semver.build}}"
authority = "v{{semver.major}}.{{semver.minor}}.{{semver.patch}}.{{semver.build}}"
